baseURL: "https://it4anxiety.github.io/"
languageCode: "fr-FR"
title: "IT4Anxiety"
theme: it4anxiety

Paginate: 3

params:
  socialShare: false

  title: "IT4Anxiety"
  description: ""
  # staticPath: ""  # The path to serve the static files from
  favicon: "/img/logo_it.png"

  theme:
    disableThemeToggle: false
    defaultTheme: "light" # dark

  footer:
    recentPosts: false
    socialNetworks:
      linkedin: https://www.linkedin.com/company/it4anxiety
      twitter: https://twitter.com/it4anxiety
      facebook: https://www.facebook.com/IT4Anxiety
      youtube: https://www.youtube.com/channel/UCFTlfH3D6GtQj1ffESYI3yg

defaultContentLanguage: en      
languages:
  en:
    params:
      # Hero
      hero:
        enable: true
        # intro: ""
        title: "IT4Anxiety"
        # subtitle: "EU Project"
        content: |
          IT4Anxiety supports the implementation of **innovative solutions** with the objective of **reducing the anxiety** of patients suffering from mental disorders. 
          More informations on the links below.
        image: "/img/IT4Anxiety_Logo.png"
        socialLinks:
          fontAwesomeIcons:
            - icon: fas fa-globe
              url: https://www.nweurope.eu/projects/project-search/it4anxiety-managing-anxiety-via-innovative-technologies-for-better-mental-health/
            - icon: fas fa-globe
              url: http://it4anxiety-wallonie.be/
            - icon: fab fa-linkedin
              url: https://www.linkedin.com/company/it4anxiety
            - icon: fab fa-twitter
              url: https://twitter.com/it4anxiety
            - icon: fab fa-youtube
              url: https://www.youtube.com/channel/UCFTlfH3D6GtQj1ffESYI3yg
            - icon: fab fa-facebook
              url: https://www.facebook.com/IT4Anxiety
      # PARTENERS
      partener:
        enable: true
        items:
          - job: "Psylaris"
            company: "Website"
            companyUrl: "https://www.psylaris.com/en/"
            content: |
              Psylaris was founded in 2017 with the mission to reduce waiting lines for mental health problems and improving therapy. Currently, Psylaris is active in over 20 countries with its Virtual Reality and online mental health solutions. Psylaris developed a VR product package (Psylaris Care) including innovative solutions for EMDR, Exposure and Relaxation therapy.
            featuredLink:
              enable: false
              name: ""
              url: ""
          - job: "Spectre Biotech"
            company: "Website"
            companyUrl: "https://www.spectre-biotech.com/"
            content: |
               Spectre Biotech wants to put brain imaging at the same level than blood test or ultrasound. It brings into the cloud all the hardware and brain expertise previously only available in research labs & scientific literature, usable in a daily routine and without any education required.
            featuredLink:
              enable: false
              name: ""
              url: ""

    
      # STARTUPS
      ourstart:
        enable: true
        items:
          - job: "Healthy Mind"
            company: "Website"
            companyUrl: "https://healthymind.fr/"
            #date: ""
            content: |
              Therapeutic virtual reality to reduce pain and anxiety. We offer healthcare professionals a medical device that combines immersion through virtual reality technology, medical hypnosis and advanced psychology principles to reduce pain and anxiety in their patients.
            featuredLink:
              enable: false
              name: ""
              url: ""
          - job: "Sentimentics"
            company: "Website"
            companyUrl: "http://www.sentimentics.com"
            #date: ""
            content: |
              Sentimentics is a business-to-business and research oriented company which offers you both REST API and on-premises solutions.
            featuredLink:
              enable: false
              name: ""
              url: ""
              
      # PROFESSIONAL
      professional:
        enable: true
        title: |-
          For professionals
        # index: true
        items:
          - title: "Training"
            school:
              name: "e-learning platform"
              url: "https://ehealth.training/"
            content: |-
              This training platform, created within the framework of the IT4Anxiety project, offers training for **health professionals**, but also for **future health professionals**.
      
      #Startup
      Startup:
        enable: true
        title: |-
          For startups
        # index: true
        items:
          - title: "Training"
            school:
              name: "150sho"
              url: "#"
            content: |-
              This 

      #User
      User:
        enable: true
        title: |-
          For users
        # index: true
        items:
          - title: "Title"
            school:
              name: "Gamian"
              url: "#"
            content: |-
              This 

      #Family
      Family:
        enable: true
        title: |-
          For families
        # index: true
        items:
          - title: "Title"
            school:
              name: "Similes"
              url: "#"
            content: |-
              This

      #Expert
      Expert:
        enable: true
        title: |-
          For experts
        # index: true
        items:
          - title: "Title"
            school:
              name: "VUA"
              url: "#"
            content: |-
              This
          - title: "Title"
            school:
              name: "UU"
              url: "#"
            content: |-
              This

      #Membership
      contact:
        enable: true
        title: Join us
        content: Do not hesitate to send us an email.
        email: projet.europeen@saintmartin.ofc.be
        btnName: Mail us