baseURL: "https://it4anxiety.github.io/"
languageCode: "fr-FR"
title: "IT4Anxiety"
theme: it4anxiety

Paginate: 3

params:
  socialShare: false

  title: "IT4Anxiety"
  description: ""
  # staticPath: ""  # The path to serve the static files from
  favicon: "/img/logo_it.png"

  theme:
    disableThemeToggle: false
    defaultTheme: "light" # dark

  footer:
    recentPosts: false
    socialNetworks:
      linkedin: https://www.linkedin.com/company/it4anxiety
      twitter: https://twitter.com/it4anxiety
      facebook: https://www.facebook.com/IT4Anxiety
      youtube: https://www.youtube.com/channel/UCFTlfH3D6GtQj1ffESYI3yg

defaultContentLanguage: en      
languages:
  en:
    params:
      # Hero
      hero:
        enable: true
        # intro: ""
        title: "IT4Anxiety"
        # subtitle: "EU Project"
        content: |
          IT4Anxiety supports the implementation of **innovative solutions** with the objective of **reducing the anxiety** of patients suffering from mental disorders. 
          More informations on the links below.
        image: "/img/IT4Anxiety_Logo.png"
        socialLinks:
          fontAwesomeIcons:
            - icon: fas fa-globe
              url: https://www.nweurope.eu/projects/project-search/it4anxiety-managing-anxiety-via-innovative-technologies-for-better-mental-health/
            - icon: fas fa-globe
              url: http://it4anxiety-wallonie.be/
            - icon: fab fa-linkedin
              url: https://www.linkedin.com/company/it4anxiety
            - icon: fab fa-twitter
              url: https://twitter.com/it4anxiety
            - icon: fab fa-youtube
              url: https://www.youtube.com/channel/UCFTlfH3D6GtQj1ffESYI3yg
            - icon: fab fa-facebook
              url: https://www.facebook.com/IT4Anxiety
      
      # Links
      professional:
        enable: true
        title: |-
          Professionals
        # index: true
        items:
          - title: "Training"
            school:
              name: "e-learning platform"
              url: "https://ehealth.training/"
            content: |-
              This training platform, created within the framework of the IT4Anxiety project, offers training for **health professionals**, but also for **future health professionals**.
      
      #Startup
      Startup:
        enable: true
        title: |-
          Start-up
        # index: true
        items:
          - title: "Training"
            school:
              name: "150sho"
              url: "#"
            content: |-
              This 

      #User
      User:
        enable: true
        title: |-
          Users
        # index: true
        items:
          - title: "Title"
            school:
              name: "Gamian"
              url: "#"
            content: |-
              This 

      #Family
      Family:
        enable: true
        title: |-
          Family
        # index: true
        items:
          - title: "Title"
            school:
              name: "Similes"
              url: "#"
            content: |-
              This

      #Expert
      Expert:
        enable: true
        title: |-
          Expert
        # index: true
        items:
          - title: "Title"
            school:
              name: "VUA"
              url: "#"
            content: |-
              This
          - title: "Title"
            school:
              name: "UU"
              url: "#"
            content: |-
              This

  fr:
    params:
       # Hero
      hero:
        enable: true
        # intro: ""
        title: "IT4Anxiety"
        # subtitle: "EU Project"
        content: |
          IT4Anxiety accompagne la mise en place de **solutions innovantes** visant à **réduire l'anxiété** des patients souffrant de troubles mentaux. 
          Vous trouverez plus d'informations sur les liens suivants.
          
        image: "/img/IT4Anxiety_Logo.png"
        socialLinks:
          fontAwesomeIcons:
            - icon: fas fa-globe
              url: https://www.nweurope.eu/projects/project-search/it4anxiety-managing-anxiety-via-innovative-technologies-for-better-mental-health/
            - icon: fas fa-globe
              url: http://it4anxiety-wallonie.be/
            - icon: fab fa-linkedin
              url: https://www.linkedin.com/company/it4anxiety
            - icon: fab fa-twitter
              url: https://twitter.com/it4anxiety
            - icon: fab fa-youtube
              url: https://www.youtube.com/channel/UCFTlfH3D6GtQj1ffESYI3yg
            - icon: fab fa-facebook
              url: https://www.facebook.com/IT4Anxiety
      
      # Links
      professional:
        enable: true
        title: |-
          Autres liens utiles
        # index: true
        items:
          - title: "Formation pour les professionnels"
            school:
              name: "plateforme d'e-learning "
              url: "https://ehealth.training/"
            content: |-
              Cette plateforme de formation réalisée dans le cadre du projet IT4Anxiety, propose des formations pour les **professionnels de santé**, mais également pour les **futurs professionnels de santé**. <br>